import { Knex } from "knex";


export async function up(knex: Knex): Promise<void> {
    return knex.schema.raw(`
        CREATE TABLE "movie" (
            "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "title" varchar NOT NULL,
            "duration" varchar NOT NULL,
            "year" integer NOT NULL,
            "origin" varchar NOT NULL
        );
    `)
}


export async function down(knex: Knex): Promise<void> {
    return knex.schema.dropTable('movie')
}

