import { Knex } from 'knex'

export async function up (knex: Knex): Promise<void> {
  return await knex.schema.raw(`
        CREATE TABLE "system-user"(
            "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "email" varchar NOT NULL UNIQUE,
            "password" varchar NOT NULL
        );`
  )
}

export async function down (knex: Knex): Promise<void> {
  return await knex.schema.dropTable('system-user')
}
