import { Knex } from "knex";


export async function up(knex: Knex): Promise<void> {
    return knex.schema.raw(`
        CREATE TABLE "person" (
            "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "name" varchar NOT NULL,
            "gender" varchar NOT NULL,
            "bornAt" date NOT NULL,
            "nacionality" varchar NOT NULL,
            "bio" text,
            "role" integer NOT NULL
        );
    `)
}


export async function down(knex: Knex): Promise<void> {
    return knex.schema.dropTable('person')
}

